name = "Litematica+"
author = "Joe Biden"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0712a898810097e599ba77a9cbdb2a9c9a00c3bd3de54738fd160786ac64918a"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
